services:
    backend:
        build:
            context: ./backend
            dockerfile: ../docker/Dockerfile-backend
        image: go-vue-backend:latest
        command: reflex -v -r '\.go$' -s go run main.go
        volumes:
            - ./backend:/app
        ports:
            - "3000:3000"

    frontend:
        build:
            context: ./frontend
            dockerfile: ../docker/Dockerfile-frontend
        image: go-vue-frontend:latest
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/app